import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AppLayout from '../../Layouts/AppLayout';
import { Database, Server, Cpu, CheckCircle2, XCircle } from 'lucide-react';
export default function Dashboard({ status, timestamp, checks, message }) {
    const checkItems = [
        { name: 'Primary Database', status: checks.database, icon: Database, desc: 'Atlas / Drizzle Connection' },
        { name: 'Redis Queue', status: checks.redis, icon: Server, desc: 'Domain Event Dispatcher' },
        { name: 'System Cache', status: checks.cache, icon: Cpu, desc: 'Performance Optimizer' },
    ];
    return (_jsx(AppLayout, { title: "System Health Dashboard", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [_jsxs("div", { className: "md:col-span-2 bg-white rounded-2xl shadow-sm border border-gray-100 p-8", children: [_jsxs("div", { className: "flex items-center justify-between mb-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-slate-900", children: "Infrastructure Nodes" }), _jsx("p", { className: "text-slate-500 text-sm", children: "Real-time status of connected services" })] }), _jsxs("div", { className: `px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider ${status === 'healthy' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`, children: ["System ", status] })] }), _jsx("div", { className: "space-y-4", children: checkItems.map((item, i) => (_jsxs("div", { className: "flex items-center justify-between p-4 rounded-xl bg-gray-50 border border-gray-100", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-10 h-10 bg-white rounded-lg flex items-center justify-center text-slate-400 shadow-sm border border-gray-100", children: _jsx(item.icon, { size: 20 }) }), _jsxs("div", { children: [_jsx("div", { className: "font-bold text-slate-800", children: item.name }), _jsx("div", { className: "text-xs text-slate-500", children: item.desc })] })] }), item.status !== false ? (_jsx(CheckCircle2, { className: "text-green-500", size: 24 })) : (_jsx(XCircle, { className: "text-red-500", size: 24 }))] }, i))) })] }), _jsxs("div", { className: "bg-slate-900 rounded-2xl shadow-lg p-8 text-white relative overflow-hidden", children: [_jsx("h3", { className: "text-lg font-bold mb-2", children: "Last Update" }), _jsx("div", { className: "text-3xl font-mono mb-8", children: new Date(timestamp).toLocaleTimeString() }), _jsxs("div", { className: "space-y-4 text-sm text-slate-400", children: [_jsxs("p", { children: [_jsx("strong", { children: "Environment:" }), " development"] }), _jsxs("p", { children: [_jsx("strong", { children: "Uptime:" }), " 99.9%"] }), _jsxs("p", { children: [_jsx("strong", { children: "Version:" }), " v1.1.0"] })] }), _jsxs("div", { className: "mt-12 p-4 bg-slate-800 rounded-xl border border-slate-700", children: [_jsx("div", { className: "text-xs text-slate-500 mb-1 uppercase font-bold tracking-widest", children: "Message" }), _jsxs("p", { className: "text-white italic", children: ["\"", message, "\""] })] })] })] }) }));
}
//# sourceMappingURL=Dashboard.js.map